#lang racket/base

;; raylib-var/config.rkt — 渲染/窗口/系统配置常量

;; ============================================================
;; 窗口标志
;; ============================================================

(define FLAG-VSYNC-HINT              64)
(define FLAG-FULLSCREEN-MODE         2)
(define FLAG-WINDOW-RESIZABLE        4)
(define FLAG-WINDOW-UNDECORATED      8)
(define FLAG-WINDOW-HIDDEN          128)
(define FLAG-WINDOW-MINIMIZED       512)
(define FLAG-WINDOW-MAXIMIZED      1024)
(define FLAG-WINDOW-UNFOCUSED      2048)
(define FLAG-WINDOW-TOPMOST        4096)
(define FLAG-WINDOW-HIGHDPI        8192)
(define FLAG-WINDOW-ALWAYS-RUN    16384)
(define FLAG-WINDOW-TRANSPARENT    32)
(define FLAG-MSAA-4X-HINT          16)
(define FLAG-BORDERLESS-WINDOWED-MODE 32768)

;; ============================================================
;; 日志级别
;; ============================================================

(define LOG-INFO      1) (define LOG-WARNING   2)
(define LOG-ERROR     4) (define LOG-DEBUG     8)

;; ============================================================
;; 相机
;; ============================================================

(define CAMERA-CUSTOM          0)
(define CAMERA-FREE            1)
(define CAMERA-ORBITAL         2)
(define CAMERA-FIRST-PERSON    3)
(define CAMERA-THIRD-PERSON    4)
(define CAMERA-PERSPECTIVE     0)
(define CAMERA-ORTHOGRAPHIC    1)

;; ============================================================
;; 字体 / 光标
;; ============================================================

(define FONT-DEFAULT 0)
(define FONT-BITMAP 1)
(define FONT-SDF 2)

(define MOUSE-CURSOR-DEFAULT 0)
(define MOUSE-CURSOR-ARROW 1)
(define MOUSE-CURSOR-IBEAM 2)
(define MOUSE-CURSOR-CROSSHAIR 3)
(define MOUSE-CURSOR-POINTING-HAND 4)
(define MOUSE-CURSOR-RESIZE-EW 5)
(define MOUSE-CURSOR-RESIZE-NS 6)
(define MOUSE-CURSOR-RESIZE-NWSE 7)
(define MOUSE-CURSOR-RESIZE-NESW 8)
(define MOUSE-CURSOR-RESIZE-ALL 9)
(define MOUSE-CURSOR-NOT-ALLOWED 10)

;; ============================================================
;; Shader uniform 类型
;; ============================================================

(define SHADER-UNIFORM-FLOAT   0)
(define SHADER-UNIFORM-VEC2    1)
(define SHADER-UNIFORM-VEC3    2)
(define SHADER-UNIFORM-VEC4    3)
(define SHADER-UNIFORM-INT     4)
(define SHADER-UNIFORM-IVEC2   5)
(define SHADER-UNIFORM-IVEC3   6)
(define SHADER-UNIFORM-IVEC4   7)
(define SHADER-UNIFORM-SAMPLER2D 8)

;; ============================================================
;; Blend 模式
;; ============================================================

(define BLEND-ALPHA          0)
(define BLEND-ADDITIVE       1)
(define BLEND-MULTIPLIED     2)
(define BLEND-ADD-COLORS     3)
(define BLEND-SUBTRACT-COLORS 4)
(define BLEND-ALPHA-PREMULTIPLY 5)
(define BLEND-CUSTOM         6)
(define BLEND-CUSTOM-SEPARATE 7)
(define RL-ZERO 0)
(define RL-ONE  1)
(define RL-SRC-ALPHA #x0302)
(define RL-FUNC-ADD #x8006)

;; ============================================================
;; NPatch 布局
;; ============================================================

(define NPATCH-NINE-PATCH             0)
(define NPATCH-THREE-PATCH-VERTICAL   1)
(define NPATCH-THREE-PATCH-HORIZONTAL 2)
(define RLGL-SRC-ALPHA   #x0302)
(define RLGL-MIN         #x8007)
(define RLGL-MAX         #x8008)

;; ============================================================
;; Material map 类型
;; ============================================================

(define MATERIAL-MAP-DIFFUSE 0)
(define MATERIAL-MAP-ALBEDO 0)
(define MATERIAL-MAP-METALNESS 1)
(define MATERIAL-MAP-NORMAL 2)
(define MATERIAL-MAP-ROUGHNESS 3)
(define MATERIAL-MAP-OCCLUSION 4)
(define MATERIAL-MAP-EMISSION 5)
(define MATERIAL-MAP-HEIGHT 6)
(define MATERIAL-MAP-CUBEMAP 7)
(define MATERIAL-MAP-IRRADIANCE 8)
(define MATERIAL-MAP-PREFILTER 9)
(define MATERIAL-MAP-BRDF 10)

;; ============================================================
;; Cubemap 布局
;; ============================================================

(define CUBEMAP-LAYOUT-AUTO-DETECT 0)
(define CUBEMAP-LAYOUT-LINE-VERTICAL 1)
(define CUBEMAP-LAYOUT-LINE-HORIZONTAL 2)
(define CUBEMAP-LAYOUT-CROSS-THREE-BY-FOUR 3)
(define CUBEMAP-LAYOUT-CROSS-FOUR-BY-THREE 4)

;; ============================================================
;; Shader location indices
;; ============================================================

(define SHADER-LOC-VERTEX-POSITION 0)
(define SHADER-LOC-VERTEX-TEXCOORD01 1)
(define SHADER-LOC-VERTEX-TEXCOORD02 2)
(define SHADER-LOC-VERTEX-NORMAL 3)
(define SHADER-LOC-VERTEX-TANGENT 4)
(define SHADER-LOC-VERTEX-COLOR 5)
(define SHADER-LOC-MATRIX-MVP 6)
(define SHADER-LOC-MATRIX-VIEW 7)
(define SHADER-LOC-MATRIX-PROJECTION 8)
(define SHADER-LOC-MATRIX-MODEL 9)
(define SHADER-LOC-MATRIX-NORMAL 10)
(define SHADER-LOC-VECTOR-VIEW 11)
(define SHADER-LOC-COLOR-DIFFUSE 12)
(define SHADER-LOC-COLOR-SPECULAR 13)
(define SHADER-LOC-COLOR-AMBIENT 14)
(define SHADER-LOC-MAP-ALBEDO      15)
(define SHADER-LOC-MAP-METALNESS   16)
(define SHADER-LOC-MAP-NORMAL      17)
(define SHADER-LOC-MAP-ROUGHNESS   18)
(define SHADER-LOC-MAP-OCCLUSION   19)
(define SHADER-LOC-MAP-EMISSION    20)
(define SHADER-LOC-MAP-HEIGHT      21)
(define SHADER-LOC-MAP-CUBEMAP     22)
(define SHADER-LOC-MAP-IRRADIANCE  23)
(define SHADER-LOC-MAP-PREFILTER   24)
(define SHADER-LOC-MAP-BRDF        25)
(define SHADER-LOC-MAP-DIFFUSE   SHADER-LOC-MAP-ALBEDO)
(define SHADER-LOC-MAP-SPECULAR  SHADER-LOC-MAP-METALNESS)

;; ============================================================
;; Texture filter / wrap 模式
;; ============================================================

(define TEXTURE-FILTER-POINT           0)
(define TEXTURE-FILTER-BILINEAR        1)
(define TEXTURE-FILTER-TRILINEAR       2)
(define TEXTURE-FILTER-ANISOTROPIC-4X  3)
(define TEXTURE-FILTER-ANISOTROPIC-8X  4)
(define TEXTURE-WRAP-REPEAT        0)
(define TEXTURE-WRAP-CLAMP         1)
(define TEXTURE-WRAP-MIRROR-REPEAT 2)
(define TEXTURE-WRAP-MIRROR-CLAMP  3)

;; ============================================================
;; Framebuffer attachment
;; ============================================================

(define RL-ATTACHMENT-COLOR-CHANNEL0 0)
(define RL-ATTACHMENT-DEPTH 100)
(define RL-ATTACHMENT-STENCIL 200)
(define RL-ATTACHMENT-TEXTURE2D 100)
(define RL-ATTACHMENT-CUBEMAP-POSITIVE-X 0)
(define RL-ATTACHMENT-RENDERBUFFER 200)

;; ============================================================
;; Pixel 格式
;; ============================================================

(define PIXELFORMAT-UNCOMPRESSED-R8G8B8A8 7)
(define PIXELFORMAT-UNCOMPRESSED-R32G32B32A32 10)

(provide
 FLAG-VSYNC-HINT FLAG-FULLSCREEN-MODE FLAG-WINDOW-RESIZABLE
 FLAG-WINDOW-UNDECORATED FLAG-WINDOW-HIDDEN
 FLAG-WINDOW-MINIMIZED FLAG-WINDOW-MAXIMIZED
 FLAG-WINDOW-UNFOCUSED FLAG-WINDOW-TOPMOST
 FLAG-WINDOW-HIGHDPI FLAG-WINDOW-ALWAYS-RUN
 FLAG-WINDOW-TRANSPARENT FLAG-MSAA-4X-HINT
 FLAG-BORDERLESS-WINDOWED-MODE

 LOG-INFO LOG-WARNING LOG-ERROR LOG-DEBUG

 CAMERA-CUSTOM CAMERA-FREE CAMERA-ORBITAL
 CAMERA-FIRST-PERSON CAMERA-THIRD-PERSON
 CAMERA-PERSPECTIVE CAMERA-ORTHOGRAPHIC

 FONT-DEFAULT FONT-BITMAP FONT-SDF

 MOUSE-CURSOR-DEFAULT MOUSE-CURSOR-ARROW MOUSE-CURSOR-IBEAM
 MOUSE-CURSOR-CROSSHAIR MOUSE-CURSOR-POINTING-HAND
 MOUSE-CURSOR-RESIZE-EW MOUSE-CURSOR-RESIZE-NS
 MOUSE-CURSOR-RESIZE-NWSE MOUSE-CURSOR-RESIZE-NESW
 MOUSE-CURSOR-RESIZE-ALL MOUSE-CURSOR-NOT-ALLOWED

 SHADER-UNIFORM-FLOAT SHADER-UNIFORM-VEC2
 SHADER-UNIFORM-VEC3 SHADER-UNIFORM-VEC4
 SHADER-UNIFORM-INT
 SHADER-UNIFORM-IVEC2 SHADER-UNIFORM-IVEC3 SHADER-UNIFORM-IVEC4
 SHADER-UNIFORM-SAMPLER2D

 BLEND-ALPHA BLEND-ADDITIVE BLEND-MULTIPLIED BLEND-ADD-COLORS
 BLEND-SUBTRACT-COLORS BLEND-ALPHA-PREMULTIPLY BLEND-CUSTOM BLEND-CUSTOM-SEPARATE
 RL-ZERO RL-ONE RL-SRC-ALPHA RL-FUNC-ADD

 NPATCH-NINE-PATCH NPATCH-THREE-PATCH-VERTICAL NPATCH-THREE-PATCH-HORIZONTAL
 RLGL-SRC-ALPHA RLGL-MIN RLGL-MAX

 MATERIAL-MAP-DIFFUSE
 MATERIAL-MAP-ALBEDO MATERIAL-MAP-METALNESS MATERIAL-MAP-NORMAL
 MATERIAL-MAP-ROUGHNESS MATERIAL-MAP-OCCLUSION
 MATERIAL-MAP-EMISSION MATERIAL-MAP-HEIGHT
 MATERIAL-MAP-CUBEMAP MATERIAL-MAP-IRRADIANCE
 MATERIAL-MAP-PREFILTER MATERIAL-MAP-BRDF

 CUBEMAP-LAYOUT-AUTO-DETECT CUBEMAP-LAYOUT-LINE-VERTICAL
 CUBEMAP-LAYOUT-LINE-HORIZONTAL
 CUBEMAP-LAYOUT-CROSS-THREE-BY-FOUR CUBEMAP-LAYOUT-CROSS-FOUR-BY-THREE

 SHADER-LOC-VERTEX-POSITION SHADER-LOC-VERTEX-TEXCOORD01
 SHADER-LOC-VERTEX-TEXCOORD02 SHADER-LOC-VERTEX-NORMAL
 SHADER-LOC-VERTEX-TANGENT SHADER-LOC-VERTEX-COLOR
 SHADER-LOC-MATRIX-MVP SHADER-LOC-MATRIX-VIEW
 SHADER-LOC-MATRIX-PROJECTION SHADER-LOC-MATRIX-MODEL
 SHADER-LOC-MATRIX-NORMAL SHADER-LOC-VECTOR-VIEW
 SHADER-LOC-COLOR-DIFFUSE SHADER-LOC-COLOR-SPECULAR
 SHADER-LOC-COLOR-AMBIENT
 SHADER-LOC-MAP-ALBEDO SHADER-LOC-MAP-METALNESS SHADER-LOC-MAP-NORMAL
 SHADER-LOC-MAP-ROUGHNESS SHADER-LOC-MAP-OCCLUSION
 SHADER-LOC-MAP-EMISSION SHADER-LOC-MAP-HEIGHT
 SHADER-LOC-MAP-CUBEMAP SHADER-LOC-MAP-IRRADIANCE
 SHADER-LOC-MAP-PREFILTER SHADER-LOC-MAP-BRDF
 SHADER-LOC-MAP-DIFFUSE SHADER-LOC-MAP-SPECULAR

 TEXTURE-FILTER-POINT TEXTURE-FILTER-BILINEAR TEXTURE-FILTER-TRILINEAR
 TEXTURE-FILTER-ANISOTROPIC-4X TEXTURE-FILTER-ANISOTROPIC-8X
 TEXTURE-WRAP-REPEAT TEXTURE-WRAP-CLAMP
 TEXTURE-WRAP-MIRROR-REPEAT TEXTURE-WRAP-MIRROR-CLAMP

 RL-ATTACHMENT-COLOR-CHANNEL0 RL-ATTACHMENT-DEPTH
 RL-ATTACHMENT-STENCIL RL-ATTACHMENT-TEXTURE2D
 RL-ATTACHMENT-CUBEMAP-POSITIVE-X RL-ATTACHMENT-RENDERBUFFER

 PIXELFORMAT-UNCOMPRESSED-R8G8B8A8 PIXELFORMAT-UNCOMPRESSED-R32G32B32A32)
