#lang racket/base

;; raylib [textures] example - raw data (Racket FFI 翻译)
;;
;; 对应 C: examples/textures/textures_raw_data.c
;;
;; 演示: 加载无文件头 RAW 图像数据 + 用代码生成棋盘格纹理

(require "../../raylib/raylib.rkt"
         racket/runtime-path
         ffi/unsafe)

;; ============================================================
;; 资源路径 (相对于源文件位置，不依赖运行目录)
;; ============================================================

(define-runtime-path resource-dir-path
  "../../../examples/textures/resources/")

(define resource-dir (path->string resource-dir-path))

;; ============================================================
;; 常量
;; ============================================================

(define screen-width 800)
(define screen-height 450)

;; raylib PixelFormat: PIXELFORMAT_UNCOMPRESSED_R8G8B8A8 = 7
(define PFORMAT-R8G8B8A8 7)

;; ============================================================
;; 初始化
;; ============================================================

(init-window screen-width screen-height
             "raylib [textures] example - raw data")

;; 加载 RAW 图像数据 (384x512, 32bit RGBA, 无文件头)
(define fudesumi-raw
  (load-image-raw (string-append resource-dir "fudesumi.raw")
                  384 512 PFORMAT-R8G8B8A8 0))
(define fudesumi (load-texture-from-image fudesumi-raw))
(unload-image fudesumi-raw)

;; ============================================================
;; 用代码生成棋盘格纹理 (CPU 端手动填充像素)
;; ============================================================

(define im-width 960)
(define im-height 480)

;; 分配像素缓冲区: 每像素 4 字节 (RGBA)
(define pixels (mem-alloc (* im-width im-height 4)))

;; ORANGE 颜色字节: R=255 G=161 B=0  A=255
;; GOLD   颜色字节: R=255 G=203 B=0  A=255
(for ([y (in-range im-height)])
  (for ([x (in-range im-width)])
    (define offset (* (+ (* y im-width) x) 4))
    (if (zero? (modulo (+ (quotient x 32) (quotient y 32)) 2))
        ;; ORANGE
        (begin (ptr-set! pixels _ubyte offset      255)
               (ptr-set! pixels _ubyte (+ offset 1) 161)
               (ptr-set! pixels _ubyte (+ offset 2) 0)
               (ptr-set! pixels _ubyte (+ offset 3) 255))
        ;; GOLD
        (begin (ptr-set! pixels _ubyte offset      255)
               (ptr-set! pixels _ubyte (+ offset 1) 203)
               (ptr-set! pixels _ubyte (+ offset 2) 0)
               (ptr-set! pixels _ubyte (+ offset 3) 255)))))

;; 构造 Image 结构体，转换为 GPU 纹理后释放 CPU 端数据
(define checked-im (list pixels im-width im-height 1 PFORMAT-R8G8B8A8))
(define checked (load-texture-from-image checked-im))
(unload-image checked-im)

(set-target-fps 60)

;; ============================================================
;; 主循环
;; ============================================================

(let loop ()
  (unless (window-should-close?)
    (begin-drawing)
    (clear-background RAYWHITE)

    ;; 半透明棋盘格背景 (居中)
    (let* ([cw (list-ref checked 1)]
           [ch (list-ref checked 2)])
      (draw-texture checked
                    (- (quotient screen-width 2) (quotient cw 2))
                    (- (quotient screen-height 2) (quotient ch 2))
                    (fade WHITE 0.5)))

    ;; RAW 图像 (Fudesumi 精灵)
    (draw-texture fudesumi 430 -30 WHITE)

    (draw-text "CHECKED TEXTURE " 84 85 30 BROWN)
    (draw-text "GENERATED by CODE" 72 148 30 BROWN)
    (draw-text "and RAW IMAGE LOADING" 46 210 30 BROWN)

    (draw-text "(c) Fudesumi sprite by Eiden Marsal" 310 (- screen-height 20) 10 BROWN)

    (end-drawing)
    (loop)))

;; ============================================================
;; 清理
;; ============================================================

(unload-texture fudesumi)
(unload-texture checked)
(close-window)
