#lang racket/base

;; raylib/raylib.rkt — 统一入口，纯转发

(require "core/lib.rkt"
         "core/ffi-helpers.rkt"
         (only-in ffi/unsafe ptr-ref ptr-set! ptr-add
                  _ubyte _float _int _uint _pointer _bool _stdbool _double _long)
         (except-in "../raylib-var/var.rkt"
                    RL-ZERO RL-ONE RL-SRC-ALPHA RL-FUNC-ADD)
         "core/rlgl.rkt"
         "core/rcore.rkt"
         "core/rshapes.rkt"
         "core/rtextures.rkt"
         "core/rtext.rkt"
         "core/rmodels.rkt"
         "core/raudio.rkt"
         "core/rcamera.rkt"
         "core/raymath.rkt"
         "core/rlights.rkt"
         "raw-types.rkt"
         "core/types/transform.rkt"
         "core/types/bone-info.rkt"
         "core/types/color.rkt"
         "core/types/vector2.rkt"
         "core/types/vector3.rkt"
         "core/types/vector4.rkt"
         "core/types/rectangle.rkt"
         "core/types/matrix.rkt"
         "core/types/camera2d.rkt"
         "core/types/camera3d.rkt"
         "core/types/ray.rkt"
         "core/types/ray-collision.rkt"
         "core/types/bounding-box.rkt"
         "core/types/image.rkt"
         "core/types/texture.rkt"
         "core/types/render-texture.rkt"
         "core/types/npatch-info.rkt"
         "core/types/glyph-info.rkt"
         "core/types/font.rkt"
         "core/types/shader.rkt"
         "core/types/material-map.rkt"
         "core/types/material.rkt"
         "core/types/model-skeleton.rkt"
         "core/types/model.rkt"
         "core/types/model-animation.rkt"
         "core/types/mesh.rkt"
         "core/types/wave.rkt"
         "core/types/audio-stream.rkt"
         "core/types/sound.rkt"
         "core/types/music.rkt"
         "core/types/vr-device-info.rkt"
         "core/types/vr-stereo-config.rkt"
         "core/types/file-path-list.rkt"
         "core/types/automation-event.rkt"
         "core/types/automation-event-list.rkt")

(provide (all-from-out
          "core/lib.rkt"
          "core/rlgl.rkt"
          "core/rcore.rkt"
          "core/rshapes.rkt"
          "core/rtextures.rkt"
          "core/rtext.rkt"
          "core/rmodels.rkt"
          "core/raudio.rkt"
          "core/rcamera.rkt"
          "core/raymath.rkt"
          "core/rlights.rkt"
          "core/types/color.rkt"
          "core/types/vector2.rkt"
          "core/types/vector3.rkt"
          "core/types/vector4.rkt"
          "core/types/rectangle.rkt"
          "core/types/matrix.rkt"
          "core/types/camera2d.rkt"
          "core/types/camera3d.rkt"
          "core/types/ray.rkt"
          "core/types/ray-collision.rkt"
          "core/types/bounding-box.rkt"
          "core/types/image.rkt"
          "core/types/texture.rkt"
          "core/types/render-texture.rkt"
          "core/types/npatch-info.rkt"
          "core/types/glyph-info.rkt"
          "core/types/font.rkt"
          "core/types/shader.rkt"
          "core/types/material-map.rkt"
          "core/types/material.rkt"
          "core/types/transform.rkt"
          "core/types/bone-info.rkt"
          "core/types/model-skeleton.rkt"
          "core/types/model.rkt"
          "core/types/model-animation.rkt"
          "core/types/mesh.rkt"
          "core/types/wave.rkt"
          "core/types/audio-stream.rkt"
          "core/types/sound.rkt"
          "core/types/music.rkt"
          "core/types/vr-device-info.rkt"
          "core/types/vr-stereo-config.rkt"
          "core/types/file-path-list.rkt"
          "core/types/automation-event.rkt"
          "core/types/automation-event-list.rkt")
         (all-from-out "../raylib-var/var.rkt")
         ptr-ref ptr-set! ptr-add
         _ubyte _float _int _uint _pointer _bool _stdbool _double _long)
