#lang racket/base
(require ffi/unsafe)
(define-cstruct _Vector4 ([x _float] [y _float] [z _float] [w _float]))
(define (vector4 x y z w)
  (let ([v (malloc _Vector4 'atomic)])
    (ptr-set! v _float 0 (exact->inexact x)) (ptr-set! v _float 1 (exact->inexact y))
    (ptr-set! v _float 2 (exact->inexact z)) (ptr-set! v _float 3 (exact->inexact w)) v))
(define (vector4-x v) (ptr-ref v _float 0))
(define (vector4-y v) (ptr-ref v _float 1))
(define (vector4-z v) (ptr-ref v _float 2))
(define (vector4-w v) (ptr-ref v _float 3))

;; pass-by-value
(define _vec4-bytes (_list-struct _float _float _float _float))
(define (vec4->bytes v)
  (list (ptr-ref v _float 0) (ptr-ref v _float 1)
        (ptr-ref v _float 2) (ptr-ref v _float 3)))
(define (bytes->vec4 lst)
  (let ([v (malloc _Vector4 'atomic)])
    (ptr-set! v _float 0 (car lst))
    (ptr-set! v _float 1 (cadr lst))
    (ptr-set! v _float 2 (caddr lst))
    (ptr-set! v _float 3 (cadddr lst))
    v))
(define (malloc-float-vec4 a b c d)
  (let ([p (malloc _float 4 'atomic)])
    (ptr-set! p _float 0 a)
    (ptr-set! p _float 1 b)
    (ptr-set! p _float 2 c)
    (ptr-set! p _float 3 d)
    p))

(provide _Vector4 _vec4-bytes vector4 vector4-x vector4-y vector4-z vector4-w
         vec4->bytes bytes->vec4 malloc-float-vec4)
