#lang racket/base

;; API 单步测试 — 画一帧等空格

(require "../helper.rkt" (prefix-in lib: "../../raylib/raylib.rkt"))

(printf "按 SPACE 推进\n")
(lib:set-config-flags lib:FLAG-VSYNC-HINT)
(lib:init-window 800 450 "API test [SPACE]")
(lib:set-target-fps 60)

(define (wait-space)
  (let loop ()
    (lib:poll-input-events)
    (lib:begin-drawing)
    (lib:draw-text "SPACE →" 700 430 15 lib:GRAY)
    (lib:end-drawing)
    (if (lib:is-key-pressed lib:KEY-SPACE) (void) (loop))))

;; === draw-circle ===
(test-section "draw-circle")
(lib:begin-drawing)
(lib:clear-background lib:BLACK)
(lib:draw-text "draw-circle (400,225) r=50 RED" 10 10 20 lib:GREEN)
(lib:draw-circle 400 225 50.0 lib:RED)
(lib:draw-text "预期: 中央红色圆" 50 300 15 lib:GRAY)
(lib:end-drawing)
(wait-space)
(test-pass! "draw-circle")

;; === draw-circle-gradient 白→透明 ===
(test-section "draw-circle-gradient 白→透明")
(lib:begin-drawing)
(lib:clear-background lib:BLACK)
(lib:draw-text "draw-circle-gradient 白→透明" 10 10 20 lib:GREEN)
(lib:draw-circle-gradient (lib:vector2 400 225) 120.0
                          (lib:color-alpha lib:WHITE 0.0) lib:WHITE)
(lib:draw-text "预期: 白色渐变(中心→边缘透明)" 50 350 15 lib:GRAY)
(lib:end-drawing)
(wait-space)
(test-pass! "draw-circle-gradient")

;; === draw-triangle-fan ===
(test-section "draw-triangle-fan 蓝")
(lib:begin-drawing)
(lib:clear-background lib:BLACK)
(lib:draw-text "draw-triangle-fan 4顶点 蓝" 10 10 20 lib:GREEN)
(lib:draw-triangle-fan
  (vector (lib:vector2 400 150) (lib:vector2 250 250)
          (lib:vector2 400 350) (lib:vector2 550 250)) 4 lib:BLUE)
(lib:draw-text "预期: 蓝色四边形" 50 350 15 lib:GRAY)
(lib:end-drawing)
(wait-space)
(test-pass! "draw-triangle-fan")

;; === draw-rectangle-lines ===
(test-section "draw-rectangle-lines")
(lib:begin-drawing)
(lib:clear-background lib:BLACK)
(lib:draw-text "draw-rectangle-lines (100,100,200,150)" 10 10 20 lib:GREEN)
(lib:draw-rectangle-lines 100 100 200 150 lib:GREEN)
(lib:draw-text "预期: 绿色空心矩形" 50 350 15 lib:GRAY)
(lib:end-drawing)
(wait-space)
(test-pass! "draw-rectangle-lines")

;; === draw-texture-pro 棋盘格 ===
(test-section "draw-texture-pro 棋盘格")
(define cb-img (lib:gen-image-checked 64 64 32 32 lib:DARKBROWN lib:DARKGRAY))
(define cb-tex (lib:load-texture-from-image cb-img))
(lib:begin-drawing)
(lib:clear-background lib:BLACK)
(lib:draw-text "draw-texture-pro 棋盘格平铺" 10 10 20 lib:GREEN)
(lib:draw-texture-pro cb-tex
  (lib:rectangle 0 0 64 64) (lib:rectangle 0 0 800 450)
  (lib:vector2 0 0) 0.0 lib:WHITE)
(lib:draw-text "预期: 棋盘格" 50 430 15 lib:GREEN)
(lib:end-drawing)
(wait-space)
(lib:unload-texture cb-tex)
(lib:unload-image cb-img)
(test-pass! "draw-texture-pro")

;; === draw-circle-gradient 红→透明 ===
(test-section "draw-circle-gradient 红→透明")
(lib:begin-drawing)
(lib:clear-background lib:BLACK)
(lib:draw-text "draw-circle-gradient 红→透明" 10 10 20 lib:GREEN)
(lib:draw-circle-gradient (lib:vector2 400 225) 100.0
                          (lib:color-alpha lib:RED 0.0) lib:RED)
(lib:draw-text "预期: 红渐变(中心透明→外缘实心)" 50 350 15 lib:GRAY)
(lib:end-drawing)
(wait-space)
(test-pass! "draw-circle-gradient 红")

;; === RT + draw-texture-rec ===
(test-section "RT + draw-texture-rec")
(define rt1 (lib:load-render-texture 400 225))
(lib:begin-texture-mode rt1)
(lib:clear-background (lib:color-alpha lib:WHITE 0.0))
(lib:draw-circle 200 112 50.0 lib:RED)
(lib:end-texture-mode)
(define rt1-tex (list (list-ref rt1 1) (list-ref rt1 2)
                      (list-ref rt1 3) (list-ref rt1 4) (list-ref rt1 5)))
(lib:begin-drawing)
(lib:clear-background lib:BLACK)
(lib:draw-text "draw-texture-rec from RT" 10 10 20 lib:GREEN)
(lib:draw-texture-rec rt1-tex (lib:rectangle 0 0 400 225)
                      (lib:vector2 200 112) lib:WHITE)
(lib:draw-text "预期: 中央红色圆" 50 430 15 lib:GREEN)
(lib:end-drawing)
(wait-space)
(lib:unload-render-texture rt1)
(test-pass! "RT + draw-texture-rec")

;; === 双RT ===
(test-section "双RT")
(define s-rt (lib:load-render-texture 400 225))
(define m-rt (lib:load-render-texture 400 225))
(lib:begin-texture-mode s-rt)
(lib:clear-background lib:BLACK)
(lib:draw-circle 200 112 50.0 lib:RED)
(lib:end-texture-mode)
(lib:begin-texture-mode m-rt)
(lib:clear-background lib:BLACK)
(lib:draw-circle-gradient (lib:vector2 200 112) 80.0
                          (lib:color-alpha lib:WHITE 0.0) lib:WHITE)
(lib:end-texture-mode)
(define s-tex (list (list-ref s-rt 1) (list-ref s-rt 2)
                    (list-ref s-rt 3) (list-ref s-rt 4) (list-ref s-rt 5)))
(lib:begin-drawing)
(lib:clear-background lib:BLACK)
(lib:draw-text "双RT + draw-texture-rec" 10 10 20 lib:GREEN)
(lib:draw-texture-rec s-tex (lib:rectangle 0 0 400 225)
                      (lib:vector2 200 112) lib:WHITE)
(lib:draw-text "预期: 红色圆" 50 430 15 lib:GREEN)
(lib:end-drawing)
(wait-space)
(lib:unload-render-texture s-rt)
(lib:unload-render-texture m-rt)
(test-pass! "双RT")

;; === 碰撞检测 ===
(test-section "碰撞检测")
(define cr (lib:rectangle 100 100 200 150))
(lib:begin-drawing)
(lib:clear-background lib:BLACK)
(lib:draw-text "check-collision" 10 10 20 lib:GREEN)
(lib:draw-rectangle-lines 100 100 200 150 lib:BLUE)
(lib:draw-rectangle-lines 120 120 100 100 lib:GREEN)
(assert-true (lib:check-collision-point-rec (lib:vector2 150 150) cr))
(assert-false (lib:check-collision-point-rec (lib:vector2 50 50) cr))
(assert-true (lib:check-collision-recs cr (lib:rectangle 120 120 100 100)))
(assert-false (lib:check-collision-recs cr (lib:rectangle 400 400 100 100)))
(lib:draw-text "断言通过" 50 350 15 lib:GREEN)
(lib:end-drawing)
(wait-space)
(test-pass! "碰撞检测")

;; === vec2 运算 ===
(test-section "vec2 运算")
(define va (lib:vector2 3.0 4.0))
(define vb (lib:vector2 1.0 2.0))
(define vn (lib:vec2-normalize va))
(assert-vec2= (lib:vec2-subtract va vb) 2.0 2.0)
(assert-vec2= (lib:vec2-add va vb) 4.0 6.0)
(assert-vec2= (lib:vec2-scale va 2.0) 6.0 8.0)
(assert-= (lib:vec2-length vn) 1.0)
(lib:begin-drawing)
(lib:clear-background lib:BLACK)
(lib:draw-text "vec2 断言通过" 10 10 20 lib:GREEN)
(lib:draw-circle 400 225 (* 50.0 (lib:vec2-length vn)) lib:YELLOW)
(lib:draw-text "黄圆 |norm|×50 = 50" 50 350 15 lib:GREEN)
(lib:end-drawing)
(wait-space)
(test-pass! "vec2 运算")

;; === blend 常量 ===
(test-section "blend 常量")
(lib:begin-drawing)
(lib:clear-background lib:BLACK)
(lib:draw-text "blend 常量 断言" 10 10 20 lib:GREEN)
(lib:draw-circle 400 225 50.0 lib:GREEN)
(lib:draw-text "有绘制内容防止残留" 50 350 15 lib:GREEN)
(lib:end-drawing)
(assert-= lib:BLEND-ALPHA 0)
(assert-= lib:BLEND-CUSTOM 4)
(assert-= lib:RLGL-SRC-ALPHA #x0302)
(assert-= lib:RLGL-MIN #x8007)
(assert-= lib:RLGL-MAX #x8008)
(wait-space)
(test-pass! "blend 常量")

;; === 关闭 ===
(lib:close-window)
(printf "全部完成~n")
