#lang racket/base
(require "../../raylib/raylib.rkt" ffi/unsafe
         (only-in ffi/unsafe ptr-set! ptr-ref _float _uint _int malloc)
         racket/runtime-path)
(define GLSL-VERSION 330)
(define-runtime-path rd "../../../examples/shaders/resources/")
(define (res . p) (path->string (simplify-path (apply build-path rd p))))
(set-config-flags FLAG-MSAA-4X-HINT)
(init-window 800 450 "lightmap debug")
(define camera (camera3d 4.0 6.0 8.0  0.0 0.0 0.0  0.0 1.0 0.0  45.0 CAMERA-PERSPECTIVE))
(define mesh (gen-mesh-plane 16.0 16.0 1 1))
(printf "vaoId=~a vboId[0]=~a vboId[1]=~a vboId[2]=~a~n"
        (list-ref mesh 15)
        (ptr-ref (list-ref mesh 17) _uint 0)
        (ptr-ref (list-ref mesh 17) _uint 1)
        (ptr-ref (list-ref mesh 17) _uint 2))
(define vertex-count (list-ref mesh 0))
(define tc2 (malloc _float (* vertex-count 2) 'atomic))
(for ([i (in-range (* vertex-count 2))]) (ptr-set! tc2 _float i 0.0))
(ptr-set! tc2 _float 2 1.0) (ptr-set! tc2 _float 4 0.0) (ptr-set! tc2 _float 6 1.0)
(ptr-set! tc2 _float 5 1.0) (ptr-set! tc2 _float 7 1.0)
(printf "tc2-vbo pre-call...~n")
(define tc2-vbo (rl-load-vertex-buffer tc2 (* vertex-count 2 4) #f))
(printf "tc2-vbo=~a~n" tc2-vbo)
(ptr-set! (list-ref mesh 17) _uint SHADER-LOC-VERTEX-TEXCOORD02 tc2-vbo)
(printf "vboId[2] now = ~a~n" (ptr-ref (list-ref mesh 17) _uint 2))
(define vao-ok (rl-enable-vertex-array (list-ref mesh 15)))
(printf "rlEnableVertexArray=~a~n" vao-ok)
(rl-set-vertex-attribute 5 2 RL-FLOAT 0 0 0)
(rl-enable-vertex-attribute 5)
(rl-disable-vertex-array)
(printf "all init done, entering loop...~n")
(set-target-fps 60)
(let loop ()
  (unless (window-should-close?)
    (update-camera camera CAMERA-ORBITAL)
    (begin-drawing)(clear-background RED)(draw-fps 10 10)(end-drawing)
    (loop)))
(close-window)
