#lang racket/base
(require "../../raylib/raylib.rkt" ffi/unsafe
         (only-in ffi/unsafe ptr-set! ptr-ref _float _uint _int malloc)
         racket/runtime-path)
(define-syntax-rule (log fmt . args)
  (begin (fprintf (current-error-port) fmt . args) (flush-output)))
(define GLSL-VERSION 330)
(define-runtime-path rd "../../../examples/shaders/resources/")
(define (res . p) (path->string (simplify-path (apply build-path rd p))))
(log "init...~n")
(set-config-flags FLAG-MSAA-4X-HINT)
(init-window 800 450 "debug")
(log "window ok~n")
(define camera (camera3d 4.0 6.0 8.0  0.0 0.0 0.0  0.0 1.0 0.0  45.0 CAMERA-PERSPECTIVE))
(log "camera ok~n")
(define mesh (gen-mesh-plane 16.0 16.0 1 1))
(log "mesh ok, vaoId=~a~n" (list-ref mesh 15))
(log "loading shader...~n")
(define shader (load-shader (res (format "shaders/glsl~a/lightmap.vs" GLSL-VERSION))
                            (res (format "shaders/glsl~a/lightmap.fs" GLSL-VERSION))))
(log "shader id=~a~n" (car shader))
(log "loading textures...~n")
(define texture (load-texture (res "cubicmap_atlas.png")))
(log "tex id=~a~n" (car texture))
(define light (load-texture (res "spark_flame.png")))
(log "light id=~a~n" (car light))
(log "creating lightmap...~n")
(define lm-rt (load-render-texture 16 16))
(log "lightmap fbo=~a tex=~a~n" (list-ref lm-rt 0) (list-ref lm-rt 1))
(log "drawing to lightmap...~n")
(begin-texture-mode lm-rt)
(clear-background BLACK)
(begin-blend-mode BLEND-ADDITIVE)
(draw-texture-pro light
 (rectangle 0.0 0.0 (exact->inexact (list-ref light 1)) (exact->inexact (list-ref light 2)))
 (rectangle 0.0 0.0 32.0 32.0) (vector2 16.0 16.0) 0.0 RED)
(begin-blend-mode BLEND-ALPHA)
(end-texture-mode)
(log "lightmap drawn~n")
(log "gen mips...~n")
(define (gen-tex-mips tex-list)
  (define ptr (malloc 20 'atomic))
  (ptr-set! ptr _uint 0 (list-ref tex-list 0))
  (ptr-set! ptr _int 1 (list-ref tex-list 1))
  (ptr-set! ptr _int 2 (list-ref tex-list 2))
  (ptr-set! ptr _int 3 (list-ref tex-list 3))
  (ptr-set! ptr _int 4 (list-ref tex-list 4))
  (gen-texture-mipmaps ptr)
  (list (ptr-ref ptr _uint 0)(ptr-ref ptr _int 1)(ptr-ref ptr _int 2)(ptr-ref ptr _int 3)(ptr-ref ptr _int 4)))
(define lm-tex (gen-tex-mips (list (list-ref lm-rt 1)(list-ref lm-rt 2)(list-ref lm-rt 3)(list-ref lm-rt 4)(list-ref lm-rt 5))))
(set-texture-filter lm-tex TEXTURE-FILTER-TRILINEAR)
(log "mips ok~n")
(log "setting up material...~n")
(define mat-ptr (load-material-default))
(set-material-shader mat-ptr shader)
(set-material-texture mat-ptr MATERIAL-MAP-ALBEDO texture)
(set-material-texture mat-ptr MATERIAL-MAP-METALNESS lm-tex)
(define mat-list (material-ptr->list mat-ptr))
(log "material ok~n")
(log "entering loop!~n")
(set-target-fps 60)
(let loop ([frame 0])
  (when (and (not (window-should-close?)) (< frame 3))
    (log "frame ~a begin...~n" frame)
    (begin-drawing)
    (log "  begin-drawing ok~n")
    (clear-background RAYWHITE)
    (log "  clear ok~n")
    (begin-mode-3d camera)
    (log "  begin-3d ok~n")
    (draw-mesh mesh mat-list (matrix-identity))
    (log "  draw-mesh ok~n")
    (end-mode-3d)
    (log "  end-3d ok~n")
    (draw-fps 10 10)
    (end-drawing)
    (log "  end-drawing ok~n")
    (loop (+ frame 1))))
(log "DONE!~n")
(close-window)
