#lang racket/base
(require "../../raylib/raylib.rkt" ffi/unsafe
         (only-in ffi/unsafe ptr-set! ptr-ref _float _uint _int malloc)
         racket/runtime-path)
(define GLSL-VERSION 330)
(define-runtime-path rd "../../../examples/shaders/resources/")
(define (res . p) (path->string (simplify-path (apply build-path rd p))))
(set-config-flags FLAG-MSAA-4X-HINT)
(init-window 800 450 "debug2")
(define camera (camera3d 4.0 6.0 8.0  0.0 0.0 0.0  0.0 1.0 0.0  45.0 CAMERA-PERSPECTIVE))

;; --- step 1: mesh + texcoords2 (known to work) ---
(define mesh (gen-mesh-plane 16.0 16.0 1 1))
(define vertex-count (list-ref mesh 0))
(define tc2 (malloc _float (* vertex-count 2) 'atomic))
(for ([i (in-range (* vertex-count 2))]) (ptr-set! tc2 _float i (if (even? i) (exact->inexact (/ (quotient i 2) 1.0)) 0.0)))
(ptr-set! tc2 _float 1 0.0) (ptr-set! tc2 _float 3 0.0) (ptr-set! tc2 _float 5 1.0) (ptr-set! tc2 _float 7 1.0)
(define tc2-vbo (rl-load-vertex-buffer tc2 (* vertex-count 2 4) #f))
(ptr-set! (list-ref mesh 17) _uint 2 tc2-vbo)
(rl-enable-vertex-array (list-ref mesh 15))
(rl-set-vertex-attribute 5 2 RL-FLOAT 0 0 0)
(rl-enable-vertex-attribute 5)
(rl-disable-vertex-array)
(printf "mesh+tc2 OK~n")

;; --- step 2: shader ---
(define shader (load-shader (res (format "shaders/glsl~a/lightmap.vs" GLSL-VERSION))
                            (res (format "shaders/glsl~a/lightmap.fs" GLSL-VERSION))))
(printf "shader loaded, id=~a~n" (car shader))

;; --- step 3: textures ---
(define texture (load-texture (res "cubicmap_atlas.png")))
(printf "texture loaded, id=~a~n" (car texture))
(define light (load-texture (res "spark_flame.png")))
(printf "light loaded, id=~a~n" (car light))

(define (gen-tex-mips tex-list)
  (define ptr (malloc 20 'atomic))
  (ptr-set! ptr _uint 0 (list-ref tex-list 0))
  (ptr-set! ptr _int 1 (list-ref tex-list 1))
  (ptr-set! ptr _int 2 (list-ref tex-list 2))
  (ptr-set! ptr _int 3 (list-ref tex-list 3))
  (ptr-set! ptr _int 4 (list-ref tex-list 4))
  (gen-texture-mipmaps ptr)
  (list (ptr-ref ptr _uint 0)(ptr-ref ptr _int 1)(ptr-ref ptr _int 2)(ptr-ref ptr _int 3)(ptr-ref ptr _int 4)))
(set! texture (gen-tex-mips texture))
(set-texture-filter texture TEXTURE-FILTER-TRILINEAR)
(printf "texture mipmaps OK~n")

;; --- step 4: lightmap ---
(define lm-rt (load-render-texture 16 16))
(printf "lightmap RT created, fbo=~a tex=~a~n" (list-ref lm-rt 0) (list-ref lm-rt 1))
(begin-texture-mode lm-rt)
(clear-background BLACK)
(begin-blend-mode BLEND-ADDITIVE)
(draw-texture-pro light
 (rectangle 0.0 0.0 (exact->inexact (list-ref light 1)) (exact->inexact (list-ref light 2)))
 (rectangle 0.0 0.0 32.0 32.0) (vector2 16.0 16.0) 0.0 RED)
(begin-blend-mode BLEND-ALPHA)
(end-texture-mode)
(printf "lightmap drawn OK~n")

(define lm-tex (gen-tex-mips (list (list-ref lm-rt 1)(list-ref lm-rt 2)(list-ref lm-rt 3)(list-ref lm-rt 4)(list-ref lm-rt 5))))
(set-texture-filter lm-tex TEXTURE-FILTER-TRILINEAR)
(printf "lightmap mipmaps OK~n")

;; --- step 5: material ---
(define mat-ptr (load-material-default))
(printf "material ptr created~n")
(set-material-shader mat-ptr shader)
(printf "material shader set~n")
(set-material-texture mat-ptr MATERIAL-MAP-ALBEDO texture)
(printf "material texture0 set~n")
(set-material-texture mat-ptr MATERIAL-MAP-METALNESS lm-tex)
(printf "material texture1 set~n")
(define mat-list (material-ptr->list mat-ptr))
(printf "material list: shader-id=~a maps-ptr=~s params=~a ~a ~a ~a~n"
        (list-ref mat-list 0) (list-ref mat-list 3)
        (list-ref mat-list 4)(list-ref mat-list 5)(list-ref mat-list 6)(list-ref mat-list 7))

;; --- step 6: render ---
(printf "entering render loop~n")
(set-target-fps 60)
(let loop ()
  (unless (window-should-close?)
    (update-camera camera CAMERA-ORBITAL)
    (begin-drawing)(clear-background RAYWHITE)
    (begin-mode-3d camera)
    (draw-mesh mesh mat-list (matrix-identity))
    (end-mode-3d)
    (draw-texture-pro lm-tex (rectangle 0.0 0.0 -16.0 -16.0)
                      (rectangle 100.0 10.0 128.0 128.0) (vector2 0.0 0.0) 0.0 WHITE)
    (draw-fps 10 10)
    (end-drawing)
    (loop)))
(close-window)
