#lang racket/base
(require "../../raylib/raylib.rkt" ffi/unsafe
         (only-in ffi/unsafe ptr-set! ptr-ref _uint _int malloc)
         racket/runtime-path)
(define-runtime-path rd "../../../examples/shaders/resources/")
(define (res . p) (path->string (simplify-path (apply build-path rd p))))
(init-window 800 450 "test")
(printf "A\n")(flush-output)
(define tex (load-texture (res "cubicmap_atlas.png")))
(printf "B: tex id=~a~n" (list-ref tex 0))(flush-output)
(define ptr (malloc 20 'atomic))
(ptr-set! ptr _uint 0 (list-ref tex 0))
(ptr-set! ptr _int 1 (list-ref tex 1))
(ptr-set! ptr _int 2 (list-ref tex 2))
(ptr-set! ptr _int 3 (list-ref tex 3))
(ptr-set! ptr _int 4 (list-ref tex 4))
(printf "C: calling GenTextureMipmaps...~n")(flush-output)
(gen-texture-mipmaps ptr)
(printf "D: mips done~n")(flush-output)
(printf "E: calling load-material-default...~n")(flush-output)
(define mat-ptr (load-material-default))
(printf "F: ptr=~s~n" mat-ptr)(flush-output)
(close-window)
(printf "DONE~n")(flush-output)
