#lang racket/base
;; raylib [shaders] example - multi sample2d (Racket FFI 翻译)
(require "../../raylib/raylib.rkt" racket/runtime-path
         ffi/unsafe (only-in ffi/unsafe ptr-set! _float malloc))
(define GLSL-VERSION 330)
(define-runtime-path resource-dir "../../../examples/shaders/resources/")
(define (res . parts) (path->string (simplify-path (apply build-path resource-dir parts))))
(init-window 800 450 "raylib [shaders] example - multi sample2d")
(define tex-cyan  (load-texture (res "plasma.png")))
(define tex-blue (load-texture (res "parrots.png")))
(define shader (load-shader #f (res (format "shaders/glsl~a/color_mix.fs" GLSL-VERSION))))
(define tex-blue-loc (get-shader-location shader "texture1"))
(define divider-loc (get-shader-location shader "divider"))
(define divider-val (malloc _float 1 'atomic))
(ptr-set! divider-val _float 0 0.5)
(set-target-fps 60)
(let loop ()
  (unless (window-should-close?)
    (let ([v (+ (ptr-ref divider-val _float 0) (* (get-mouse-wheel-move) 0.05))])
      (ptr-set! divider-val _float 0 (clamp 0.0 v 1.0)))
    (set-shader-value shader divider-loc divider-val SHADER-UNIFORM-FLOAT)
    (begin-drawing) (clear-background RAYWHITE)
    (begin-shader-mode shader)
    (set-shader-value-texture shader tex-blue-loc tex-blue)
    (draw-texture tex-cyan 0 0 WHITE)
    (end-shader-mode)
    (draw-text "Use mouse wheel to move the mixing region between the two textures." 10 10 20 GRAY)
    (draw-fps 690 10) (end-drawing) (loop)))
(unload-texture tex-cyan) (unload-texture tex-blue) (unload-shader shader) (close-window)
