#!/bin/bash
# build-all.sh — compile and run all struct layout probes
# Usage: cd tools && bash build-all.sh

set -e
cd "$(dirname "$0")"

INC="-I../../src"
STRUCTS=(Shader MaterialMap Material Mesh Transform BoneInfo ModelSkeleton Model ModelAnimation RayCollision)

echo ";; === Auto-generated layout constants ==="
echo ";; Generated by tools/build-all.sh"
echo ""

for s in "${STRUCTS[@]}"; do
    src="${s}-layout.c"
    bin="${s}-layout"
    gcc $INC "$src" -o "$bin"
    ./"$bin"
    echo ""
done

echo "(provide (all-defined-out))"
