/* gen-layout.c — (legacy all-in-one) offsetof/sizeof → Racket layout constants
 *
 * DEPRECATED: 此文件已被拆分为独立的 per-struct 文件 (Shader-layout.c 等)。
 * 推荐使用 build-all.sh 编译运行所有独立文件，或单独编译目标结构体文件。
 *
 * 单独编译: gcc -I../../src Xxx-layout.c -o Xxx-layout && ./Xxx-layout
 * 全部编译: bash build-all.sh
 */
#include <stdio.h>
#include <stddef.h>
#include "../src/raylib.h"

int main() {
    puts(";; auto-generated by gen-layout.c (legacy all-in-one) — do not edit\n");

    /* ---- Shader ---- */
    printf("(define Shader-size %zu)\n", sizeof(Shader));
    printf("(define Shader-id-off %zu)\n", offsetof(Shader, id));
    printf("(define Shader-locs-off %zu)\n", offsetof(Shader, locs));

    /* ---- MaterialMap ---- */
    printf("(define MaterialMap-size %zu)\n", sizeof(MaterialMap));
    printf("(define MaterialMap-texture-off %zu)\n", offsetof(MaterialMap, texture));
    printf("(define MaterialMap-color-off %zu)\n", offsetof(MaterialMap, color));
    printf("(define MaterialMap-value-off %zu)\n", offsetof(MaterialMap, value));

    /* ---- Material ---- */
    printf("(define Material-size %zu)\n", sizeof(Material));
    printf("(define Material-shader-off %zu)\n", offsetof(Material, shader));
    printf("(define Material-maps-off %zu)\n", offsetof(Material, maps));
    printf("(define Material-params-off %zu)\n", offsetof(Material, params));

    /* ---- Mesh ---- */
    printf("(define Mesh-size %zu)\n", sizeof(Mesh));
    printf("(define Mesh-vertexCount-off %zu)\n", offsetof(Mesh, vertexCount));
    printf("(define Mesh-triangleCount-off %zu)\n", offsetof(Mesh, triangleCount));
    printf("(define Mesh-vertices-off %zu)\n", offsetof(Mesh, vertices));
    printf("(define Mesh-texcoords-off %zu)\n", offsetof(Mesh, texcoords));
    printf("(define Mesh-texcoords2-off %zu)\n", offsetof(Mesh, texcoords2));
    printf("(define Mesh-normals-off %zu)\n", offsetof(Mesh, normals));
    printf("(define Mesh-tangents-off %zu)\n", offsetof(Mesh, tangents));
    printf("(define Mesh-colors-off %zu)\n", offsetof(Mesh, colors));
    printf("(define Mesh-indices-off %zu)\n", offsetof(Mesh, indices));
    printf("(define Mesh-boneCount-off %zu)\n", offsetof(Mesh, boneCount));
    printf("(define Mesh-boneIndices-off %zu)\n", offsetof(Mesh, boneIndices));
    printf("(define Mesh-boneWeights-off %zu)\n", offsetof(Mesh, boneWeights));
    printf("(define Mesh-animVertices-off %zu)\n", offsetof(Mesh, animVertices));
    printf("(define Mesh-animNormals-off %zu)\n", offsetof(Mesh, animNormals));
    printf("(define Mesh-vaoId-off %zu)\n", offsetof(Mesh, vaoId));
    printf("(define Mesh-vboId-off %zu)\n", offsetof(Mesh, vboId));

    /* ---- Transform ---- */
    printf("(define Transform-size %zu)\n", sizeof(Transform));
    printf("(define Transform-translation-off %zu)\n", offsetof(Transform, translation));
    printf("(define Transform-rotation-off %zu)\n", offsetof(Transform, rotation));
    printf("(define Transform-scale-off %zu)\n", offsetof(Transform, scale));

    /* ---- BoneInfo ---- */
    printf("(define BoneInfo-size %zu)\n", sizeof(BoneInfo));
    printf("(define BoneInfo-name-off %zu)\n", offsetof(BoneInfo, name));
    printf("(define BoneInfo-parent-off %zu)\n", offsetof(BoneInfo, parent));

    /* ---- ModelSkeleton ---- */
    printf("(define ModelSkeleton-size %zu)\n", sizeof(ModelSkeleton));
    printf("(define ModelSkeleton-boneCount-off %zu)\n", offsetof(ModelSkeleton, boneCount));
    printf("(define ModelSkeleton-bones-off %zu)\n", offsetof(ModelSkeleton, bones));
    printf("(define ModelSkeleton-bindPose-off %zu)\n", offsetof(ModelSkeleton, bindPose));

    /* ---- Model ---- */
    printf("(define Model-size %zu)\n", sizeof(Model));
    printf("(define Model-transform-off %zu)\n", offsetof(Model, transform));
    printf("(define Model-meshCount-off %zu)\n", offsetof(Model, meshCount));
    printf("(define Model-materialCount-off %zu)\n", offsetof(Model, materialCount));
    printf("(define Model-meshes-off %zu)\n", offsetof(Model, meshes));
    printf("(define Model-materials-off %zu)\n", offsetof(Model, materials));
    printf("(define Model-meshMaterial-off %zu)\n", offsetof(Model, meshMaterial));
    printf("(define Model-skeleton-off %zu)\n", offsetof(Model, skeleton));
    printf("(define Model-currentPose-off %zu)\n", offsetof(Model, currentPose));
    printf("(define Model-boneMatrices-off %zu)\n", offsetof(Model, boneMatrices));

    /* ---- ModelAnimation ---- */
    printf("(define ModelAnimation-size %zu)\n", sizeof(ModelAnimation));
    printf("(define ModelAnimation-name-off %zu)\n", offsetof(ModelAnimation, name));
    printf("(define ModelAnimation-boneCount-off %zu)\n", offsetof(ModelAnimation, boneCount));
    printf("(define ModelAnimation-keyframeCount-off %zu)\n", offsetof(ModelAnimation, keyframeCount));
    printf("(define ModelAnimation-keyframePoses-off %zu)\n", offsetof(ModelAnimation, keyframePoses));

    puts("\n(provide (all-defined-out))");
    return 0;
}
