#lang racket/base
;; raylib [shapes] example - simple particles (Racket FFI 翻译)
(require "../../raylib/raylib.rkt" racket/math)
(define MAX-P 3000) (define WATER 0) (define SMOKE 1) (define FIRE 2)
(define TN (vector "WATER" "SMOKE" "FIRE"))
(define DEG2RAD (/ pi 180.0)) (define screen-w 800) (define screen-h 450)

(init-window screen-w screen-h "raylib [shapes] example - simple particles")
(set-target-fps 60)
(define er (box -2)) (define ct (box WATER))
(define emitter (vector2 (/ screen-w 2) (/ screen-h 2)))

(define px (make-vector MAX-P)) (define pv (make-vector MAX-P))
(define pr (make-vector MAX-P 0.0)) (define pc (make-vector MAX-P))
(define pl (make-vector MAX-P 0.0)) (define pa (make-vector MAX-P #f))
(define head (box 0)) (define tail (box 0))

(define (add!)
  (if (not (= (modulo (add1 (unbox head)) MAX-P) (unbox tail)))
      (let ([i (unbox head)]) (set-box! head (modulo (add1 i) MAX-P)) i) #f))

(define (emit! x y t)
  (define i (add!))
  (when i
    (vector-set! px i (vector2 x y)) (vector-set! pa i #t) (vector-set! pl i 0.0)
    (define sp (/ (random 10) 5.0)) (define d (* (random 360) DEG2RAD))
    (vector-set! pv i (vector2 (* sp (cos d)) (* sp (sin d))))
    (case t
      [(WATER) (vector-set! pr i 5.0) (vector-set! pc i BLUE)]
      [(SMOKE) (vector-set! pr i 7.0) (vector-set! pc i GRAY)]
      [(FIRE)  (vector-set! pr i 10.0) (vector-set! pc i YELLOW)
               (define v (vector-ref pv i))
               (ptr-set! v _float 0 (* (ptr-ref v _float 0) 0.1))
(define (update!)
  (let loop ([i (unbox tail)])
    (when (not (= i (unbox head)))
      (define pos (vector-ref px i)) (define vel (vector-ref pv i))
      (define x (ptr-ref pos _float 0)) (define y (ptr-ref pos _float 1))
      (define vx (ptr-ref vel _float 0)) (define vy (ptr-ref vel _float 1))
      (define r (vector-ref pr i)) (define c (vector-ref pc i))
      (vector-set! pl i (+ (vector-ref pl i) 1/60))
      (when (or (< x (- r)) (> x (+ screen-w r)) (< y (- r)) (> y (+ screen-h r)))
        (vector-set! pa i #f))
      (when (vector-ref pa i)
        (cond
          [(eq? c BLUE) (ptr-set! pos _float 0 (+ x vx)) (ptr-set! vel _float 1 (+ vy 0.2))
                        (ptr-set! pos _float 1 (+ y (ptr-ref vel _float 1)))]
          [(eq? c GRAY) (ptr-set! pos _float 0 (+ x vx)) (ptr-set! vel _float 1 (- vy 0.05))
                        (ptr-set! pos _float 1 (+ y (ptr-ref vel _float 1)))
                        (vector-set! pr i (+ r 0.5))
                        (ptr-set! c _ubyte 3 (max 0 (- (ptr-ref c _ubyte 3) 4)))
                        (when (< (ptr-ref c _ubyte 3) 4) (vector-set! pa i #f))]
          [(eq? c YELLOW)
           (ptr-set! pos _float 0 (+ x vx (* (cos (* (vector-ref pl i) 215.0)) 1.0)))
           (ptr-set! vel _float 1 (- vy 0.05))
           (ptr-set! pos _float 1 (+ y (ptr-ref vel _float 1)))
           (vector-set! pr i (- r 0.15))
           (ptr-set! c _ubyte 1 (max 0 (- (ptr-ref c _ubyte 1) 3)))
           (when (<= (vector-ref pr i) 0.02) (vector-set! pa i #f))]))
      (loop (modulo (add1 i) MAX-P)))))

(define (clean!)
  (let loop ()
    (when (and (not (= (unbox tail) (unbox head))) (not (vector-ref pa (unbox tail))))
      (set-box! tail (modulo (add1 (unbox tail)) MAX-P)) (loop))))

(define (draw!)
  (let loop ([i (unbox tail)])
    (when (not (= i (unbox head)))
      (when (vector-ref pa i) (draw-circle-v (vector-ref px i) (vector-ref pr i) (vector-ref pc i)))
      (loop (modulo (add1 i) MAX-P)))))

(let main-loop ()
  (unless (window-should-close?)
    (define e (unbox er)) (define t (unbox ct))
    (define ex (ptr-ref emitter _float 0)) (define ey (ptr-ref emitter _float 1))
    (if (< e 0) (when (= (random (- e)) 0) (emit! ex ey t))
        (for ([k (in-range (add1 e))]) (emit! ex ey t)))
    (update!) (clean!)
    (when (is-key-pressed KEY-UP)    (set-box! er (add1 e)))
    (when (is-key-pressed KEY-DOWN)  (set-box! er (- e 1)))
    (when (is-key-pressed KEY-RIGHT) (set-box! ct (if (= t FIRE) WATER (add1 t))))
    (when (is-key-pressed KEY-LEFT)  (set-box! ct (if (= t WATER) FIRE (- t 1))))
    (when (is-mouse-button-down MOUSE-BUTTON-LEFT)
      (ptr-set! emitter _float 0 (exact->inexact (get-mouse-x)))
      (ptr-set! emitter _float 1 (exact->inexact (get-mouse-y))))
    (begin-drawing) (clear-background RAYWHITE) (draw!)
    (draw-rectangle 5 5 315 75 (fade SKYBLUE 0.5))
    (draw-rectangle-lines 5 5 315 75 BLUE)
    (draw-text "CONTROLS:" 15 15 10 BLACK)
    (draw-text "UP/DOWN: Rate  LEFT/RIGHT: Type" 15 35 10 BLACK)
    (draw-text (format "~a | Type: ~a" (if (< e 0) (format "Every ~a frames" (- e))
                                            (format "~a/frame" (add1 e)))
                       (vector-ref TN t))
               15 95 10 DARKGRAY)
    (draw-fps (- screen-w 80) 10) (end-drawing) (main-loop)))
(close-window)

               (ptr-set! v _float 1 (* (ptr-ref v _float 1) 0.1))])))
