#lang racket/base
;; raylib [shapes] example - digital clock (Racket FFI 翻译)
;; SPACE 切换 7 段数码管 / 模拟表盘
(require "../../raylib/raylib.rkt" racket/math racket/date)

(define CLOCK-DIGITAL 1) (define CLOCK-ANALOG 0)
(define deg2rad (/ pi 180.0))

(define (ha h m) (- (+ (* (modulo h 12) 30.0) (* m 0.5)) 90))
(define (ma m s) (- (+ (* m 6.0) (* s 0.1)) 90))
(define (sa s) (- (* s 6.0) 90))

(set-config-flags FLAG-MSAA-4X-HINT)
(init-window 800 450 "raylib [shapes] example - digital clock")
(set-target-fps 60)

(define clock-mode (box CLOCK-DIGITAL))
(define (sec) (date-second (current-date)))
(define (min) (date-minute (current-date)))
(define (hr)  (date-hour (current-date)))

(define seg-len 60) (define seg-thick 20)
(define seg-bits (vector #b00111111 #b00000110 #b01011011 #b01001111
                         #b01100110 #b01101101 #b01111101 #b00000111
                         #b01111111 #b01101111))

(define (draw-seg center vert color)
  (define l seg-len) (define t seg-thick)
  (define cx (ptr-ref center _float 0)) (define cy (ptr-ref center _float 1))
  (if (not vert)
    (draw-triangle-strip (vector
      (vector2 (- cx (/ l 2) (/ t 2)) cy)
      (vector2 (- cx (/ l 2)) (+ cy (/ t 2)))
      (vector2 (- cx (/ l 2)) (- cy (/ t 2)))
      (vector2 (+ cx (/ l 2)) (+ cy (/ t 2)))
      (vector2 (+ cx (/ l 2)) (- cy (/ t 2)))
      (vector2 (+ cx (/ l 2) (/ t 2)) cy)) 6 color)
    (draw-triangle-strip (vector
      (vector2 cx (- cy (/ l 2) (/ t 2)))
      (vector2 (- cx (/ t 2)) (- cy (/ l 2)))
      (vector2 (+ cx (/ t 2)) (- cy (/ l 2)))
      (vector2 (- cx (/ t 2)) (+ cy (/ l 2)))
      (vector2 (+ cx (/ t 2)) (+ cy (/ l 2)))
      (vector2 cx (+ cy (/ l 2) (/ t 2)))) 6 color)))

(define (draw-7s pos seg on off)
  (define px (ptr-ref pos _float 0)) (define py (ptr-ref pos _float 1))
  (draw-seg (vector2 (+ px seg-thick (/ seg-len 2)) (+ py seg-thick))
    #f (if (bitwise-bit-set? seg 0) on off))
  (draw-seg (vector2 (+ px seg-thick seg-len (/ seg-thick 2))
              (+ py (* 2 seg-thick) (/ seg-len 2) (* -6)))
    #t (if (bitwise-bit-set? seg 1) on off))
  (draw-seg (vector2 (+ px seg-thick seg-len (/ seg-thick 2))
              (+ py (* 4 seg-thick) seg-len (/ seg-len 2) (* -18)))
    #t (if (bitwise-bit-set? seg 2) on off))
  (draw-seg (vector2 (+ px seg-thick (/ seg-len 2))
              (+ py (* 5 seg-thick) (* 2 seg-len) (* -24)))
    #f (if (bitwise-bit-set? seg 3) on off))
  (draw-seg (vector2 (+ px (/ seg-thick 2))
              (+ py (* 4 seg-thick) seg-len (/ seg-len 2) (* -18)))
    #t (if (bitwise-bit-set? seg 4) on off))
  (draw-seg (vector2 (+ px (/ seg-thick 2))
              (+ py (* 2 seg-thick) (/ seg-len 2) (* -6)))
    #t (if (bitwise-bit-set? seg 5) on off))
  (draw-seg (vector2 (+ px seg-thick (/ seg-len 2))
              (+ py (* 3 seg-thick) seg-len (* -12)))
    #f (if (bitwise-bit-set? seg 6) on off)))

(define (draw-digit pos val on off)
  (when (<= 0 val 9) (draw-7s pos (vector-ref seg-bits val) on off)))

(define (draw-digital pos h m s)
  (define px (ptr-ref pos _float 0)) (define py (ptr-ref pos _float 1))
  (define sep (if (even? s) RED (fade LIGHTGRAY 0.3)))
  (define off (fade LIGHTGRAY 0.3))
  (draw-digit (vector2 px py) (quotient h 10) RED off)
  (draw-digit (vector2 (+ px 120) py) (modulo h 10) RED off)
  (draw-circle (exact-round (+ px 240)) (exact-round (+ py 70)) 12.0 sep)
  (draw-circle (exact-round (+ px 240)) (exact-round (+ py 150)) 12.0 sep)
  (draw-digit (vector2 (+ px 260) py) (quotient m 10) RED off)
  (draw-digit (vector2 (+ px 380) py) (modulo m 10) RED off)
  (draw-circle (exact-round (+ px 500)) (exact-round (+ py 70)) 12.0 sep)
  (draw-circle (exact-round (+ px 500)) (exact-round (+ py 150)) 12.0 sep)
  (draw-digit (vector2 (+ px 520) py) (quotient s 10) RED off)
  (draw-digit (vector2 (+ px 640) py) (modulo s 10) RED off))

(define (draw-analog pos sl)
  (define px (ptr-ref pos _float 0)) (define py (ptr-ref pos _float 1))
  (draw-circle-v pos (+ sl 40.0) LIGHTGRAY) (draw-circle-v pos 12.0 GRAY)
  (for ([i (in-range 60)])
    (define a (* deg2rad (- (* 6.0 i) 90.0)))
    (define e (if (= (modulo i 5) 0) 6 10))
    (define t (if (= (modulo i 5) 0) 3.0 1.0))
    (draw-line-ex (vector2 (+ px (* (+ sl e) (cos a))) (+ py (* (+ sl e) (sin a))))
                  (vector2 (+ px (* (+ sl 20) (cos a))) (+ py (* (+ sl 20) (sin a)))) t DARKGRAY))
  (define s (sec)) (define m (min)) (define h (hr))
  (draw-rectangle-pro (rectangle px py (exact->inexact sl) 3)
                      (vector2 0.0 1.5) (sa s) MAROON)
  (draw-rectangle-pro (rectangle px py 130 7) (vector2 0.0 3.5) (ma m s) DARKGRAY)
  (draw-rectangle-pro (rectangle px py 100 7) (vector2 0.0 3.5) (ha h m) BLACK))

(let main-loop ()
  (unless (window-should-close?)
    (when (is-key-pressed KEY-SPACE)
      (set-box! clock-mode (if (= (unbox clock-mode) CLOCK-DIGITAL) CLOCK-ANALOG CLOCK-DIGITAL)))
    (define cm (unbox clock-mode)) (define s (sec)) (define m (min)) (define h (hr))
    (begin-drawing) (clear-background RAYWHITE)
    (if (= cm CLOCK-ANALOG) (draw-analog (vector2 400 240) 140)
        (draw-digital (vector2 30 60) h m s))
    (define (pad2 n) (if (< n 10) (format "0~a" n) (format "~a" n)))
    (define ts (format "~a:~a:~a" (pad2 h) (pad2 m) (pad2 s)))
    (define ms (if (= cm CLOCK-DIGITAL) "DIGITAL" "ANALOGUE"))
    (draw-text (format "Press [SPACE] to switch: ~a" ms) 10 10 20 DARKGRAY)
    (draw-text ts (- (quotient (get-screen-width) 2) (quotient (measure-text ts 150) 2)) 300 150 BLACK)
    (end-drawing) (main-loop)))
(close-window)
